[project]
name = "harmonicdrive"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.13.5"
dependencies = [
    "matplotlib>=3.10.6",
    "nfs",
    "nicegui[highcharts]>=2.24.2",
    "numpy>=2.3.3",
]

[tool.uv.sources]
nfs = { path = "../NFS", editable = true }
